---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - MAKEFLAGS="--environment-overrides --warn-undefined-variables"
    - REPOSITORY=osism/template
  matrix:
    - VERSION=latest

before_script:
  - make lint

script:
  - make build
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    make security-scan;
    fi

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    make publish;
    fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
